name: hpcc-ce
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: HPCCSystems Platform
description: |
  HPCCSystems Platform

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  hpcc-ce:
    # See 'snapcraft plugins'
    plugin: cmake
    source: ../HPCC-Platform
    configflags: 
        - -DMAKE_SNAP=ON
        - -DWSSQL_SERVICE=OFF

    prime:
      - opt/*
      - usr/*
      - var/snap/*


apps:

  hpcc-init:
    command: opt/HPCCSystems/etc/init.d/hpcc-init

  dafilesrv:
    command: opt/HPCCSystems/bin/dafilesrv

  daliadmin:
    command: opt/HPCCSystems/bin/daliadmin

  daserver:
    command: opt/HPCCSystems/bin/daserver

  dalidiag:
    command: opt/HPCCSystems/bin/dalidiag

  dfuplus:
    command: opt/HPCCSystems/bin/dfuplus

  dfuserver:
    command: opt/HPCCSystems/bin/dfuserver

  eclagent:
    command: opt/HPCCSystems/bin/eclagent

  eclccserver:
    command: opt/HPCCSystems/bin/eclccserver

  eclplus:
    command: opt/HPCCSystems/bin/eclplus

  eclscheduler:
    command: opt/HPCCSystems/bin/eclscheduler

  saserver:
    command: opt/HPCCSystems/bin/saserver

  saserver:
    command: opt/HPCCSystems/bin/saserver

  esp:
    command: opt/HPCCSystems/bin/esp

  frunssh:
    command: opt/HPCCSystems/bin/frunssh

  roxie:
    command: opt/HPCCSystems/bin/roxie

  thormasterlcr:
    command: opt/HPCCSystems/bin/thormaster_lcr

  thorslavelcr:
    command: opt/HPCCSystems/bin/thorslave_lcr

  updtdalienv:
    command: opt/HPCCSystems/bin/updtdalienv

  wuget:
    command: opt/HPCCSystems/bin/wuget

  wutool:
    command: opt/HPCCSystems/bin/wutool


#hooks:
#  install:
#    plugs: [home, network]
