#!/bin/bash
set -e -x
################################################################################
#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems®.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
################################################################################

#${SNAP_COMMON}/etc/init.d/hpcc-init stop || :
snap run hpcc-ce.hpcc-init stop || :
#${SNAP_COMMON}/etc/init.d/dafilesrv stop || :
snap run hpcc-ce.dafilesrv stop || :


